import type { IconDefinition } from '@fortawesome/fontawesome-svg-core';

export const themes = ['dark', 'light'] as const;
export type Theme = (typeof themes)[number];

export type NavLink = {
	target: {
		href: string;
		newTab?: boolean;
	};
	content: {
		text?: string;
		icon?: IconDefinition;
	};
};

// Generated by https://quicktype.io

export interface APIResponse {
	root: File;
}

export interface File {
	path: string;
	name: string;
	children: File[] | undefined;
	size: number;
	type: string;
	mtime: string;
	extension: string;
	isEditable: boolean | undefined;
}